import { QUIZ_SCORING } from '../scoring';

export const QUIZ_DEFAULTS = {
  TIME_LIMIT_MINUTES: QUIZ_SCORING.DEFAULT_TIME_LIMIT_MINUTES,
  PASSING_SCORE_PERCENT: QUIZ_SCORING.MIN_PASSING_SCORE_PERCENT,
  PERFECT_SCORE_BONUS: QUIZ_SCORING.PERFECT_SCORE_BONUS,
} as const;

export const QUIZ_LIMITS = {
  MIN_QUESTIONS: 1,
  MAX_QUESTIONS: 50,
  MIN_TIME_LIMIT_MINUTES: 5,
  MAX_TIME_LIMIT_MINUTES: 180,
} as const;
